# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishSymbols@1
  displayName: 'Publish symbols path:'
  inputs:
   SearchPattern: '**\bin\**\*.pdb'
  continueOnError: true

- task: CopyFiles@1
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
   SourceFolder: '$(build.sourcedirectory)'
   Contents: |
    **\bin\$(BuildConfiguration)\**
    src\*.testsettings
    TargetFolder: '$(build.artifactstagingdirecory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: frop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed() 